PRECISION  = DOUBLE
PROFILE    = FALSE
DEBUG      = FALSE

DIM        = 3

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE

USE_EB = TRUE

HYP_TYPE = MOL

Eos_dir     := GammaLaw
Transport_dir := Constant
Chemistry_Model = Null

Bpack   := ./Make.package
Blocs   := .

# define the location of the PELE top directory
PELEC_HOME := ../../..
include $(PELEC_HOME)/Exec/Make.PeleC
