PRECISION  = DOUBLE

PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

DIM        = 3

COMP	   = Intel

USE_MPI    = TRUE

USE_REACT  = TRUE

HYP_TYPE = MOL

# define the location of the PELE top directory
PELE_HOME  := ../../../..

# This sets the EOS directory in $(PELE_PHYSICS_HOME)/Eos
Eos_dir     := GammaLaw

# This sets the network directory in $(PELE_PHYSICS_HOME)/Reactions
Reactions_dir := Null_air

# This sets the transport directory in $(PELE_PHYSICS_HOME)/Transport
Transport_dir := Constant

Bpack   := ./Make.package
Blocs   := .

include ../../Make.PeleC
