#!/bin/bash
#SBATCH --job-name=bstep
#SBATCH --partition=standard
#SBATCH --nodes=10
#SBATCH --ntasks-per-node=36
#SBATCH --time=48:00:00
#SBATCH --account=exact
#SBATCH --output=bstep.out
#SBATCH --error=bstep.err
module purge
module load intel-mpi/2018.0.3
srun -n 360 ./PeleC3d.intel.MPI.ex inputs.3d
