PRECISION  = DOUBLE
USE_EB     = FALSE
PROFILE    = FALSE
DEBUG      = FALSE
DIM        = 3
COMP	   = gnu
USE_MPI    = FALSE
USE_OMP    = FALSE

Eos_dir     := GammaLaw
Transport_dir := Constant
Chemistry_Model := Null

Bpack   := ./Make.package
Blocs   := .

# define the location of the PELE top directory
PELEC_HOME    := ../../..
include $(PELEC_HOME)/Exec/Make.PeleC
