#!/bin/bash
#PBS -N pistcyl
#PBS -A exact
#PBS -q batch-h
#PBS -l walltime=48:00:00
#PBS -l nodes=16:ppn=24
#PBS -l qos=high

module purge
module load openmpi-gcc
mpirun -n 384 ./PeleC3d.gnu.MPI.ex inputs.3d amr.max_level=2
