! DO NOT EDIT THIS FILE!!!
!
! This file is automatically generated by write_probin.py at
! compile-time.
!
! To add a runtime parameter, do so by editting the appropriate _parameters
! file.

! This module stores the runtime parameters.  The probin_init() routine is
! used to initialize the runtime parameters

module extern_probin_module

  use amrex_fort_module, only : rt => amrex_real

  implicit none

  private

  real (kind=rt), save, public :: small_massfrac = 1.d-30
  !$acc declare create(small_massfrac)
  real (kind=rt), save, public :: react_T_min = 200.d0
  !$acc declare create(react_T_min)
  real (kind=rt), save, public :: react_T_max = 5000.d0
  !$acc declare create(react_T_max)
  real (kind=rt), save, public :: react_rho_min = 1.e-10
  !$acc declare create(react_rho_min)
  real (kind=rt), save, public :: react_rho_max = 1.e10
  !$acc declare create(react_rho_max)
  logical, save, public :: use_bulk_viscosity = .true.
  !$acc declare create(use_bulk_viscosity)

end module extern_probin_module

subroutine runtime_init(name,namlen)

  use extern_probin_module

  implicit none

  integer :: namlen
  integer :: name(namlen)

  integer :: un, i, status

  integer, parameter :: maxlen = 256
  character (len=maxlen) :: probin


  namelist /extern/ small_massfrac
  namelist /extern/ react_T_min
  namelist /extern/ react_T_max
  namelist /extern/ react_rho_min
  namelist /extern/ react_rho_max
  namelist /extern/ use_bulk_viscosity

  small_massfrac = 1.d-30
  react_T_min = 200.d0
  react_T_max = 5000.d0
  react_rho_min = 1.e-10
  react_rho_max = 1.e10
  use_bulk_viscosity = .true.


  ! create the filename
  if (namlen > maxlen) then
     print *, 'probin file name too long'
     stop
  endif

  do i = 1, namlen
     probin(i:i) = char(name(i))
  end do


  ! read in the namelist
  un = 9
  open (unit=un, file=probin(1:namlen), form='formatted', status='old')
  read (unit=un, nml=extern, iostat=status)

  if (status < 0) then
     ! the namelist does not exist, so we just go with the defaults
     continue

  else if (status > 0) then
     ! some problem in the namelist
     print *, 'ERROR: problem in the extern namelist'
     stop
  endif

  close (unit=un)

  !$acc update &
  !$acc device(small_massfrac, react_T_min, react_T_max) &
  !$acc device(react_rho_min, react_rho_max, use_bulk_viscosity)

end subroutine runtime_init

