#User-specific source files
list(APPEND PELEC_EXTRA_SOURCES ${CMAKE_SOURCE_DIR}/Exec/RegTests/MMS/probdata.f90)
list(APPEND PELEC_EXTRA_SOURCES ${CMAKE_SOURCE_DIR}/Exec/RegTests/MMS/Prob_nd.F90)
list(APPEND PELEC_EXTRA_SOURCES ${CMAKE_SOURCE_DIR}/Exec/RegTests/MMS/bc_fill_nd.F90)
list(APPEND PELEC_EXTRA_SOURCES ${CMAKE_SOURCE_DIR}/Exec/RegTests/MMS/Prob.cpp)

#Compile-time options for executable
set(PELEC_DIM 2)
set(PELEC_ENABLE_EB ON)
set(PELEC_ENABLE_MASA ON)
set(PELEC_ENABLE_REACTIONS OFF)
set(PELEC_ENABLE_MOL ON)
set(PELEC_ENABLE_PARTICLES OFF)
set(PELEC_EOS_MODEL GammaLaw)
set(PELEC_REACTIONS_MODEL Null)
set(PELEC_TRANSPORT_MODEL Constant)
